#
# syntax: https://docs.docker.com/compose/yml/
# author: cuongnb14@gmail.com
#

version: "2"

services:

    filebeat:
        image: prima/filebeat:5.0-rc
        volumes:
            - ./filebeat-config/filebeat.yml:/filebeat.yml
            - /home/elk/logs/api.request.log:/logs/request.log
        hostname: filebeat
        domainname: filebeat.lan
        cpu_shares: 512             # 0.5 CPU
        mem_limit: 536870912        # 512 MB RAM
        #privileged: true
        #restart: always
        #stdin_open: true
        tty: true
        logging:
            driver: "json-file"
            options:
                max-size: "100M"
                max-file: "3"
